<script>

    require([
        'jquery',
        'Magento_Customer/js/customer-data'
    ], function($, customerData) {

        $(document).on('ajax:addToCart', (event) => {
            navigator.serviceWorker.controller.postMessage({update: 'cart'});
        });

        $(document).on('ajax:removeFromCart', (event) => {
            navigator.serviceWorker.controller.postMessage({update: 'cart'});
        });

        function updateCart() {
            var sections = ['cart'];
            customerData.invalidate(sections);
            customerData.reload(sections, true);
        }

        if ('serviceWorker' in navigator) {
            navigator.serviceWorker
                .register('/sw.js')
                .then(function() {
                    return navigator.serviceWorker.ready;
                })
                .then(function(reg) {
                    navigator.serviceWorker.addEventListener('message', function(event){
                        updateCart();
                    });
                }).catch(function(error) {
                    console.error(error);
                });
        }
    });


</script>
